security:
    encoders:
        FH\Bundle\AppBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        app:
            entity:
                class:          FH\Bundle\AppBundle\Entity\User
                property:       code

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        frontend:
            pattern:            ^/
            anonymous:          true
            form_login:
                login_path:     user_login
                provider:       app
                check_path:     /login_check
            logout:
                path:           user_logout
                target:         home

    access_control:
        - { path: ^/, role: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
