FH\Bundle\AppBundle\Entity\QuestionAnswer:
    type: entity
    table: question_answer

    id:
        id:
            type:           integer
            generator:
                strategy:   AUTO
            options:
                unsigned:   true

    fields:
        createdAt:
            column:         created_at
            type:           datetime
        correct:
            type:           boolean

    manyToOne:
        user:
            targetEntity:   FH\Bundle\AppBundle\Entity\User
            inversedBy:     questionAnswers
            joinColumn:
                nullable:   false
                onDelete:   CASCADE
        question:
            targetEntity:   FH\Bundle\AppBundle\Entity\Question
            joinColumn:
                nullable:   false
                onDelete:   CASCADE
