FH\Bundle\AppBundle\Entity\User:
    type: entity
    table: user

    id:
        id:
            type:           integer
            generator:
                strategy:   AUTO
            options:
                unsigned:   true

    fields:
        firstName:
            column:         first_name
            type:           string
            length:         120
        surname:
            type:           string
            length:         120
        code:
            type:           integer
            unique:         true
        image:
            type:           string
            length:         120

    oneToMany:
        consumptionsFetched:
            targetEntity:   FH\Bundle\AppBundle\Entity\Consumption
            mappedBy:       fetcher
        consumptionsReceived:
            targetEntity:   FH\Bundle\AppBundle\Entity\Consumption
            mappedBy:       receiver
        questionAnswers:
            targetEntity:   FH\Bundle\AppBundle\Entity\QuestionAnswer
            mappedBy:       user
