FH\Bundle\AppBundle\Entity\User:
    type: entity
    table: user

    id:
        id:
            type:           integer
            generator:
                strategy:   AUTO
            options:
                unsigned:   true

    fields:
        firstName:
            column:         first_name
            type:           string
            length:         120
        surname:
            type:           string
            length:         120
        code:
            type:           integer
            unique:         true
        image:
            type:           string
            length:         120
