services:
    fh_app.menu_builder:
        class: FH\Bundle\AppBundle\Menu\MenuBuilder
        arguments:
            - @knp_menu.factory
    fh_app.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: fh_app.menu_builder
        factory_method: createMainMenu
        scope: request
        arguments:
            - @request
        tags:
            - { name: knp_menu.menu, alias: main }