services:
    app.service.login_user:
        class: FH\Bundle\AppBundle\User\LoginUser
        arguments:
            - @security.token_storage
            - @security.authentication.manager

    app.service.session_provider:
        class: FH\Bundle\AppBundle\Session\SessionProvider
        arguments:
            - @session
